Repository SSAFY-ZIPZIP/zipzip-backend, pull requests merged in 2024-11, with the labels that each got.

#23 #21 setting: mysql-domain 모듈 build.gradle에 querydsl 의존성 추가
  domain/zipzip-mysql-domain/build.gradle
Labels: 🐰 예슬, ⚙️ setting

#27 #26 feat: 우리.zip 삭제 API 개발
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/controller/WorkspaceController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/service/WorkspaceService.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspaceMember/service/WorkspaceMemberService.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceRepositoryImpl.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspaceMember/repository/WorkspaceMemberJpaRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspaceMember/repository/WorkspaceMemberRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspaceMember/repository/WorkspaceMemberRepositoryImpl.java
Labels: 🐮 수빈, ✨ feat

#33 feat: 우리.zip에 초대하기 (초대 이메일 링크 전송) / 우리.zip 초대 수락하기 API 개발
  app/zipzip-api-app/build.gradle
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/ZipzipAppApiApplication.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/common/config/SecurityConfig.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/common/email/service/EmailService.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/common/filter/JwtAuthenticationFilter.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/common/jwt/JwtTokenProvider.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/member/service/MemberSerivce.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/controller/WorkspaceController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/dto/SendWorkspaceInviteRequest.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/dto/WorkspaceIdAndEmailDto.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/service/WorkspaceService.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspaceMember/service/WorkspaceMemberService.java
  common/zipzip-exception-common/src/main/java/org/ssafy/zipzipexceptioncommon/exception/ErrorMessage.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/member/repository/MemberJpaRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/member/repository/MemberRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/member/repository/MemberRepositoryImpl.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceJpaRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceRepositoryImpl.java
Labels: 🐮 수빈, ✨ feat

#35 fix: 깃 충돌 해결 시, 누락된 부분 수정
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/controller/WorkspaceController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/service/WorkspaceService.java
Labels: 🐮 수빈, 🔨fix

#42 feat: 나의 우리.zip 리스트 조회 API 개발
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/controller/WorkspaceController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/dto/GetWorkspaceResponse.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/service/WorkspaceService.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/dto/GetWorkspaceQueryDto.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceJpaRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspace/repository/WorkspaceRepositoryImpl.java
Labels: 🐮 수빈, ✨ feat

#39 feat: 관심 있는 청약 리스트 조회 API 개발
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscription/controller/SubscriptionController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscription/service/SubscriptionService.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscriptionFavorite/dto/GetFavoriteSubscriptionListResponse.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/subscription/dto/FavoriteSubscriptionDto.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/subscription/repository/SubscriptionQueryDslRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/subscription/repository/SubscriptionRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/subscription/repository/SubscriptionRepositoryImpl.java
Labels: 🐰 예슬, ✨ feat

#48 feat: 우리.zip에 부동산 추가 API 개발
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/propertyDeal/controller/PropertyDealController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/propertyDeal/service/PropertyDealService.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/controller/WorkspaceController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/dto/PostWorkspacePropertyRequest.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/service/WorkspaceService.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspacePropertyDeal/service/WorkspacePropertyDealService.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspacePropertyDeal/repository/WorkspacePropertyDealJpaRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspacePropertyDeal/repository/WorkspacePropertyDealRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspacePropertyDeal/repository/WorkspacePropertyDealRepositoryImpl.java
Labels: 🐮 수빈, ✨ feat

#53 fix: invite link에 null 들어가는 부분 수정, findIdByEmail 쿼리 명시적 작성
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/service/WorkspaceService.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/member/repository/MemberJpaRepository.java
Labels: 🐮 수빈, ✨ feat

#50 feat: 현재 검색어로 시작하는 부동산 조회 API 개발
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/propertyDeal/controller/PropertyDealController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/propertyDeal/dto/GetPropertyNameListResponse.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/propertyDeal/service/PropertyDealService.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/propertyDeal/repository/PropertydealJpaRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/propertyDeal/repository/PropertydealRepository.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/propertyDeal/repository/PropertydealRepositoryImpl.java
Labels: 🐮 수빈, ✨ feat

#54 refactor: 중간 테이블 controller 제거 및 로직 구현 위치 수정
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscription/controller/SubscriptionController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscription/service/SubscriptionService.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscriptionFavorite/controller/SubscriptionFavoriteController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscriptionProfile/controller/SubscriptionProfileController.java
Labels: 🐰 예슬, ♻️ refactor

#67 feat: mybatis로 우리.zip 리스트 조회 API 개발
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/ZipzipAppApiApplication.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/controller/WorkspaceController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/workspace/service/WorkspaceService.java
  domain/zipzip-mysql-domain/build.gradle
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspaceMybatis/config/MyBatisConfig.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/workspaceMybatis/mapper/WorkspaceMapper.java
  domain/zipzip-mysql-domain/src/main/resources/mappers/WorkspaceMapper.xml
  settings.gradle
Labels: 🐮 수빈, ✨ feat

#56 fix : category와 region 모두 description 내려가도록 수정
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/subscription/dto/SubscriptionFavoriteQueryResponseDto.java
  domain/zipzip-mysql-domain/src/main/java/org/ssafy/zipzipmysqldomain/subscription/dto/SubscriptionQueryResponseDto.java
Labels: 🐰 예슬, 🔨fix

#66 feat: 청약 관련 챗봇 서비스 기능 개발
  app/zipzip-api-app/build.gradle
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/ZipzipAppApiApplication.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscription/controller/SubscriptionController.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscription/dto/GetSubscriptionChatbotRequest.java
  app/zipzip-api-app/src/main/java/org/ssafy/zipzipapiapp/subscription/dto/GetSubscriptionChatbotResponse.java
  client/zipzip-gpt-client/build.gradle
  client/zipzip-gpt-client/src/main/java/org/ssafy/zipzipgptclient/client/ChatGPTClient.java
  client/zipzip-gpt-client/src/main/java/org/ssafy/zipzipgptclient/config/GptFeignClientConfig.java
  client/zipzip-gpt-client/src/main/java/org/ssafy/zipzipgptclient/dto/ChatGPTRequest.java
  client/zipzip-gpt-client/src/main/java/org/ssafy/zipzipgptclient/dto/ChatGPTResponse.java
  client/zipzip-gpt-client/src/main/java/org/ssafy/zipzipgptclient/dto/Choice.java
  client/zipzip-gpt-client/src/main/java/org/ssafy/zipzipgptclient/dto/Message.java
  client/zipzip-gpt-client/src/main/java/org/ssafy/zipzipgptclient/service/ChatGPTService.java
  client/zipzip-kakao-client/src/main/java/org/ssafy/zipzipkakaoclient/config/KakaoFeignClientConfig.java
  settings.gradle
Labels: 🐰 예슬, ✨ feat
